#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const generatedDir = join(root, 'generated');
if (!existsSync(generatedDir)) mkdirSync(generatedDir, { recursive: true });

const args = new Map(process.argv.slice(2).map((arg) => {
  const [key, value = 'true'] = arg.replace(/^--/, '').split('=');
  return [key, value];
}));

const routesPath = args.get('routes') || join(root, 'optimization-results', 'models', 'playbooks', 'current-walk-forward-scalp-routes.json');
const out = args.get('out') || join(generatedDir, 'scalp_route_overrides.pine');
const maxRoutes = Number(args.get('max-routes') || 80);
const tier = args.get('tier') || 'recentProfitElite';

const data = JSON.parse(readFileSync(routesPath, 'utf8'));
const tierFilters = {
  allValidated: (route) => route,
  highWin: (route) => route.test.winRate >= 70 && route.test.trades >= 5,
  elite: (route) => route.test.winRate >= 80 && route.test.trades >= 5,
  profitFirst: (route) => route.test.trades >= 5 && route.test.avgDollars >= 350 && route.test.winRate >= 60,
  profitFirstElite: (route) => route.test.trades >= 5 && route.test.avgDollars >= 400 && route.test.winRate >= 75,
  recentStableElite: (route) => route.test.trades >= 5 && route.test.winRate >= 75 && route.recent?.trades >= 2 && route.recent.winRate >= 75 && route.recent.netDollars > 0,
  recentProfitElite: (route) => route.test.trades >= 5 && route.test.winRate >= 75 && route.test.avgDollars >= 400 && route.recent?.trades >= 2 && route.recent.winRate >= 75 && route.recent.netDollars > 0,
};

const filter = tierFilters[tier] || tierFilters.recentProfitElite;
const routes = (data.validated || [])
  .filter(filter)
  .sort((a, b) => (b.test.winRate - a.test.winRate) || (b.test.avgDollars - a.test.avgDollars))
  .slice(0, maxRoutes);

function esc(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function lineFor(route) {
  const ticker = esc(route.symbol);
  const session = esc(route.session);
  const direction = esc(route.direction);
  const target = Number(route.combo.targetR || 0.35).toFixed(2);
  const stopBars = Number(route.combo.timeStopBars || 6);
  const winRate = Number(route.test.winRate || 0).toFixed(1);
  const avgDollars = Number(route.test.avgDollars || 0).toFixed(0);
  const triggerMode = esc(route.combo.triggerMode || 'base');
  const alphaQuality = Number(route.combo.minAlphaQuality || 0);
  return `    _ticker == "${ticker}" ? ["${session}", "${direction}", "${triggerMode}", ${target}, ${stopBars}, ${winRate}, ${avgDollars}, ${alphaQuality}] :`;
}

const pine = `// Generated by scripts/export_pine_scalp_routes.js
// Source: ${routesPath}
// Tier: ${tier}
// Generated: ${new Date().toISOString()}
//
// Paste this block near your Pine helper functions, then call:
// [routeSession, routeDirection, routeTriggerMode, routeTargetR, routeTimeStopBars, routeWinRate, routeAvgDollars, routeMinAlphaQuality] = f_scalpRouteForTicker(syminfo.ticker)
// Use these values to override the Scalp optimizer inputs when Auto Route Mode is enabled.

f_scalpRouteForTicker(string _ticker) =>
${routes.map(lineFor).join('\n')}
    ["All", "both", "base", 0.50, 9, 0.0, 0.0, 0]
`;

writeFileSync(out, pine);
console.log(`Pine scalp route overrides saved: ${out}`);
console.log(`Routes exported: ${routes.length}`);
